version: '3.8'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend-network

  auth-service:
    image: auth-service
    build:
      context: ./services/AuthService
      dockerfile: Dockerfile
    ports: 
      - "5100:5100"
      - "5101:5101"
    networks:
      - backend-network

  redirector-service:
    image: redirector-service
    build:
      context: ./services/RedirectorService
      dockerfile: Dockerfile
    ports:
        - "5200:5200"
        - "5201:5201"
    networks:
      - backend-network

  shortener-service:
    image: shortener-service
    build:
      context: ./services/ShortenerService
      dockerfile: Dockerfile
    ports:
        - "5300:5300"
        - "5301:5301"
    networks:
      - backend-network

  analytics-service:
    image: analytics-service
    build:
      context: ./services/AnalyticsService
      dockerfile: Dockerfile
    ports:
        - "5400:5400"
        - "5401:5401"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge