apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: kubelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: authservice:latest
          imagePullPolicy: Never 
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: ConnectionStrings__DefaultConnection
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: Jwt__Key
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: Jwt__Audience 
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: Jwt__Issuer 

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

