apiVersion: v1
kind: Secret
metadata:
  name: shorten-db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=  
---
apiVersion: v1
kind: Service
metadata:
  name: shorten-db-service
spec:
  ports:
    - port: 5432
  selector:
    app: shorten-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorten-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorten-db
  template:
    metadata:
      labels:
        app: shorten-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: shortendb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shorten-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          emptyDir: {}

