apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorten-service
  namespace: kubelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorten-service
  template:
    metadata:
      labels:
        app: shorten-service
    spec:
      containers:
        - name: shorten-service
          image: shortenservice:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: shorten-db-secret
                  key: ConnectionStrings__DefaultConnection
---
apiVersion: v1
kind: Service
metadata:
  name: shorten-service
  namespace: kubelink
spec:
  selector:
    app: shorten-service
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

